### PR TITLE
Remove slack link from homepage (and replace it with...?)

### PR DESCRIPTION
**Pull request by nevrome**
I suggest to remove the slack link from the website to silently abandon this dead chat.

We have discussed this plenty of times and I understand the argument that an active user community may need a chat eventually. But the current slack channel is de-facto an abandoned wasteland filled with the ruins of unreadable, pay-walled conversations.

One idea we discussed in the past was to create a very simple, openly read-accessible single chatroom for Poseidon, e.g. with [Gitter](https://gitter.im/). Here's an example how this might look: https://app.gitter.im/#/room/#bigchaindb_bigchaindb:gitter.im

I would be OK with something like this. Or we just abandon the idea of a chat entirely. I personally prefer people to open proper GitHub issues.

### CODE REVIEW

**Comment by stschiff** [comment]
Funny that you just thought of this, because I also thought of this right this morning. I've also become a fan of bitter, but I think for now we should wait a bit and see whether there is a need. What I would do, though, is make an advertisement for the HAMM-Slack channel. I can make a suggestion how to add that.

**Comment by nevrome** [comment]
I tried to integrate your idea visually with the rest of the landing page, @stschiff. This also involved shortening the proposed text a bit. If you don't like that, then we can go back to the previous iteration and start again.

**Comment by nevrome** [comment]
I also think the Gitter chat will require some more love. I wonder how much work it would be to cross-post the mastodon posts there. But this doesn't have the highest priority, of course.

**Review by TCLamnidis — APPROVED** [review]

**Comment by stschiff** [comment]
Yes, and I can only say I'm utterly confused here. I actually _did_ create a gitter "space" called Poseidon, with our Logo, but somehow that doesn't trickle down to the room. I don't get it yet.

**Comment by stschiff** [comment]
This is how it looks for me
image

**Comment by stschiff** [comment]
OK, I like the new layout, @nevrome, nicely done. I think this is good to merge. The one thing I was unsure of, though, is the link to the room, which somehow I can't actually create from within the gitter app. I essentially looked how bioconda advertises their room and somewhat hacked the URL. It seems to work, but it would of course be better if we could be sure. When I click "Invite" and then "share this room", it somehow stalls. Anyone of you has more luck?

**Comment by nevrome** [comment]
`share this room` works for me but only leads to a selection page for various client apps. Whatever you did certainly works better.

I will merge this now - I think we will learn more about Gitter/Matrix over time.

**Pull request merged**
