### PR TITLE
Improved the description for age information in .janno files

### PR DESCRIPTION
**Pull request by nevrome**
As announced in https://github.com/poseidon-framework/poseidon-schema/pull/68 here are some changes to the more verbose description of age information in the .janno file.

### CODE REVIEW

**Review by stschiff — APPROVED** [review]
Looks good.

**Comment by AyGhal** [comment]
Looks good to me too. Thank you!

**Review by AyGhal — APPROVED** [review]

**Comment by AyGhal** [comment]
I just have a question as I was looking at the other issue (#68) as well. 
If the fields `Date_C14_Labnr `, `Date_C14_Uncal_BP` and `Date_C14_Uncal_BP_Err ` are filled then the `Date_Type` is always `C14`? But does this mean that the date is coming from the individual itself, or just that it is useful for computational analysis? 
And if we choose `contextual `, we do not report the three columns mentioned above. Even if they are provided by the author or are in the SI information.

**Comment by nevrome** [comment]
1. If the fields `Date_C14_Labnr `, `Date_C14_Uncal_BP` and `Date_C14_Uncal_BP_Err ` are filled then the `Date_Type` is always `C14`?

    Yes.

2. But does this mean that the date is coming from the individual itself, or just that it is useful for computational analysis?

    The date does not have to come from the individual. Sometimes a date from another object from the grave gives an arguably better estimate of the year of death. There is for example the so called "old man effect", which causes too old radiocarbon dates for old individuals under certain circumstances. "contextual" just means there is no radiocarbon date that can serve as a good direct estimate, so we fall back to an age range (which may in turn be informed by a radiocarbon date).

3. And if we choose `contextual `, we do not report the three columns mentioned above. Even if they are provided by the author or are in the SI information.

    Yes. I don't see, though, why we would not choose "C14" in this case. Why would we overrule the author?

**Comment by AyGhal** [comment]
Thanks so much for clarification. 
I guess I was still a bit confused with the old way of handling it (before we had individual for `C14`). 
Of course we would not overrule the author. All good now.

**Review by AyGhal — APPROVED** [review]

**Pull request merged**
