### PR TITLE
A more detailed repo submission guide

### PR DESCRIPTION
**Pull request by nevrome**
This is supposed to implement this idea: https://github.com/poseidon-framework/published_data/issues/85

### CODE REVIEW

**Comment by nevrome** [comment]
Please see this draft for a submission guide. Check it closely in light of the experiences we recently had with the many packages prepared by you, Dana.

Maybe @sc13-bioinf has a second to read through it, too. Afaik you were the only person who ever really went through the exact steps outlined here. Did I miss something important?

**Comment by 93Boy** [comment]
In my point of view, this is very detailed even for a beginner. Only a little suggestion we can list out very common errors of this process in both git and trident such as validation fail errors and trident data mismatches. Because it happens to me occasionally and I always ask Clemence for help :smile:

**Review by stschiff — APPROVED** [review]
Great. Ready to merge. Remind me on the policy? Does the creator of a PR merge it, or someone else, like myself?

**Comment by nevrome** [comment]
@93Boy: Good point. Maybe this could be added later as an FAQ section.

@stschiff: Usually the creator of a PR should merge. But feel free to do it - this is only the website, not some code that could break. I was just wondering if @AyGhal wanted to chime in as well.

**Comment by stschiff** [comment]
I think it's OK to merge!

**Pull request merged**
