### PR TITLE
trident v1.5.7.3

### PR DESCRIPTION
**Pull request by nevrome**
Minimal update for v1.5.7.0.

@stschiff I'm not sure if we should describe the reading of gzipped archives and .vcf files already.  At the moment both features are half-baked (no writing) and experimental. What do you think?

### CODE REVIEW

**Comment by stschiff** [comment]
I think we should definitely describe the new input formats. I wouldn't describe them as "half-baked". It's definitely a cool new feature that Poseidon packages can have zipped files. People can just manually zip them if they want. I think whether or not two specific sub-commands (`forge` and `genoconvert`) can _write_ them is independent. 

I am happy to suggest that change to this PR. Thanks for remembering to update the Webpage.

**Comment by nevrome** [comment]
I'm skeptical, Stephan. As long as the writing is not there I see few practical use-cases. And the documentation of these features will be easier when they are complete, because they can just be added to the list of supported file formats.

Remember to move the old v1.5.4.0 documentation to the archive when you create the new v1.5.7.0 version.

**Comment by stschiff** [comment]
OK, I've made the changes. How can I trigger the add_pdf workflow?

I am happy to talk in person why I think writing of VCFs and zipped files is a minor detail as opposed to reading.

**Comment by nevrome** [comment]
You convinced me that this update is sensible :+1:

The .pdf generation should be triggered automatically when merging into the master branch, if the new archive document was added to the [pdf_conversion_list.tsv](https://github.com/poseidon-framework/poseidon-framework.github.io/blob/master/pdf_conversion/pdf_conversion_list.tsv).

Beyond the changes you already made I think we also have to include the `--vcffile` option to the command line documentation of most other subcommands, not just `init`.

**Review by stschiff — APPROVED** [review]
Sorry, I thought I'd already reviewed this. Looks all good. Good to merge, sorry for the delay!

**Pull request merged**
