### PR TITLE
Archive explorer

### PR DESCRIPTION
**Pull request by nevrome**
Development branch for the archive explorer.

### CODE REVIEW

**Comment by stschiff** [comment]
Is this ready for review? And how does this branch and PR relate to the other explorer branches?

**Comment by nevrome** [comment]
Sorry for the late reply, but this is not meant for merging yet. This is @dhananjaya93's dev branch. Dhana had some trouble setting this up, so we went through it together. I'll make it a draft branch. Sorry again for wasting your time.

**Comment by stschiff** [comment]
Hi Dana. OK, so I've looked at this. I am not sure I fully understand the UI just yet.

- I see that the user can choose between "Table View" and "List View", but what's the purpose of the "List view"?
- The "Map View" appears empty right now. I see a world map, but no individuals on it, even if I select a package
- I don't fully understand what the "Show Selection" button does. 
- Below the table, it always says "...fetching data from poseidon package server", even if the table is already there.
- I like the search bar, which works very snappy... but I don't fully understand what is being searched. For example, if I input "schiffels", among other packages I get to see 2014_LazaridisNature, which I wasn't part of... (but perhaps I am listed as maintainer or something?)
- I think we commented already somewhere else that we would like the table to be a bit tidier, so basically listing the title, the description, and then perhaps a single column joining Version, last-modified, Poseidon-Version and Individuals for better overview.

Happy to discuss more on Friday.

**Comment by stschiff** [comment]
Additional comments from Meeting on Aug 25:

- List view not necessary ATM
- Table view -> perhaps some interactivity. Ideas:
  - Download link
  - Button to highlight samples from this package in the map

**Comment by nevrome** [comment]
I made some changes today, most of them related to the todo list by @stschiff above. Here are some remaining todos for you @93Boy (as discussed on mattermost). Actually it's just a list of more or less concrete design ideas I had today.

- The data loading needs some tweaks:
   - [ ] We currently load all package versions. I think we should only show the latest versions on the website. With @stschiff's recent changes to the API it will soon be easy to identify the latest version for each package. This will also reduce the loading time of the map a bit.
   - Not a todo here, but an interesting observation: We could add an API feature to list only the individuals for one package, @stschiff.
- The overall layout is still incomplete and not sufficiently modern:
    - [ ] We need a robust, clear and fast search/filter feature. I'm not sure how to make it search through all sorts of variables while still communicating clearly why a given entry was included in the result. Maybe we could show the match-conditions when hovering the entry with the mouse?
    - [ ] Replacing the package table with a list of divs still sounds like a good idea to me. Gives us more flexibility. It would be brilliant if we could use bootstrap's cards-feature for that...
    - [ ] Each package div should have the most important information and some buttons. Maybe the package title, the description (truncated and in a small font), the SNP-set (this info is difficult to get right now, right, @stschiff?), a download button and a button to open the modal with the rest of the information.
- The package modal I made is pretty rudimentary and needs a number of additions and changes:
    - [ ] It currently works with a fixed height and width and some other hacky css. That won't be compatible with phones, I guess. It would be so much better to switch to a professional layouting framework like bootstrap for this! I just fear this interferes with docsify, which comes with its own css .
    - [ ] The table in the modal should include additional .janno variables. Not all of them, though... Maybe group, age, country and a button to show the rest? Maybe a table is not even the right way to display this.
    - [ ] For each sample we should have a button to show it on a map. Maybe it's actually better to have a per-package map **in** the modal. Then we don't need to solve the problem how to jump to the overall map upon selection (both for individuals and packages).
    - [ ] The modal should not just include the sample table (?) and the per-package map (?), but also general package information that is currently hidden on the top level in the details block.
- I think the map only needs some small adjustments:
   - [ ] The popup should be more informative and include more information for each sample.
   - [ ] We should communicate somehow how many samples in the current data selection have no spatial information and are therefore not on the map.
   - [ ] Maybe we could use the marker shape to express whether a sample is modern or ancient.

All of this sounds like a lot, but I  think it's actually pretty parsimonious, given the crazy things we **could** theoretically do.

**Comment by stschiff** [comment]
> Not a todo here, but an interesting observation: We could add an API feature to list only the individuals for one package, @stschiff.

Excellent idea. Yes, I'll add that as an issue to poseidon-hs

**Comment by nevrome** [comment]
Hm - Ok. But then we should decide what exactly is included in the first release. Maybe the following list is realistic?

- [ ] Filter the package and individual lists in javascript to only the latest package versions.
- [ ] Make the search box a bit more beautiful and add information about which variables are searched.
- [ ] Make the archive selection a bit more beautiful.
- [ ] Hide the modal for now by commenting out the code and hiding the magnifying glass button.
- [ ] Fix line breaks in the sample popups in the map.

I hoped we would be able to match the functionality of the R website right away. But if we want to release this asap, then this would be a possible minimum.

**Pull request merged**
